# set base image
FROM node

# create project dir
RUN mkdir -p /app/client

# select working dir
WORKDIR /app/client

# copy package-lock.json
COPY package-lock.json /app/client/

# copy package.json
COPY package*.json /app/client/

# install dependencies
RUN npm install

# copy rest of the files
COPY ./ /app/client/

# Runs the client
CMD ["npm", "run", "start"]

# mac http://127.0.0.1:3000/
# docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image_id>

# win http://192.168.99.100:3000/
# winpty docker run -it -p 3000:3000 -v /app/node_modules -v "/$(PWD)":/app -e CHOKIDAR_USEPOLLING=true <image_id>
