# set base image
FROM node

# install nodemon globally
RUN npm install -g nodemon

# create project dir
# RUN mkdir /app
RUN mkdir -p /app/server

# select working dir
# WORKDIR /app
WORKDIR /app/server

# copy package-lock.json
COPY package-lock.json /app/server/

# copy package.json
# COPY package*.json ./
COPY package*.json /app/server/

# install dependencies
RUN npm install

# copy rest of the files
# COPY ./ ./
COPY ./ /app/server/

# startup command
CMD ["npm", "run", "server"]

# mac http://127.0.0.1:3000/
# docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image_id>

# win http://192.168.99.100:3000/
# winpty docker run -it -p 3000:3000 -v /app/node_modules -v "/$(PWD)":/app -e CHOKIDAR_USEPOLLING=true <image_id>
