version: "3"
services:
  server:
    image: tamplier2911/applify-server-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV
      - PORT
      - DB
      - DB_LOCAL
      - DB_PASSWORD
      - DB_USERNAME
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - JWT_COOKIE_EXPIRES_IN
      - EMAIL_FROM
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
      - EMAIL_HOST
      - EMAIL_PORT
      - SENDGRID_USERNAME
      - SENDGRID_PASSWORD
    ports:
      - ${PORT}:${PORT}
    command: npm run start
    links:
      - db
    restart: always

  client:
    image: tamplier2911/applify-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SERVE_IMAGE_DEV
      - REACT_APP_SERVE_IMAGE_PROD
    ports:
      - 80:80
    links:
      - server
    restart: always

  db:
    image: mongo
    env_file:
      - ./client/.env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: DB_PASSWORD
