const feedbacksTypes = {
  SEND_FEEDBACK_START: "SEND_FEEDBACK_START",
  SEND_FEEDBACK_SUCCESS: "SEND_FEEDBACK_SUCCESS",
  SEND_FEEDBACK_FAILURE: "SEND_FEEDBACK_FAILURE",
  DELETE_FEEDBACK_START: "DELETE_FEEDBACK_START",
  DELETE_FEEDBACK_SUCCESS: "DELETE_FEEDBACK_SUCCESS",
  DELETE_FEEDBACK_FAILURE: "DELETE_FEEDBACK_FAILURE",
  LOAD_FEEDBACKS_START: "LOAD_FEEDBACKS_START",
  LOAD_FEEDBACKS_SUCCESS: "LOAD_FEEDBACKS_SUCCESS",
  LOAD_FEEDBACKS_FAILURE: "LOAD_FEEDBACKS_FAILURE",
  GET_MORE_FEEDS: "GET_MORE_FEEDS"
};

export default feedbacksTypes;
