const projectsTypes = {
  SET_CURRENT_PROJECT_FIRST: "SET_CURRENT_PROJECT_FIRST",
  SET_CURRENT_PROJECT_SECOND: "SET_CURRENT_PROJECT_SECOND",
  SET_CURRENT_PROJECT_THIRD: "SET_CURRENT_PROJECT_THIRD",
  SET_CURRENT_PROJECT_FOURTH: "SET_CURRENT_PROJECT_FOURTH",
  SET_CURRENT_PROJECT_NEXT: "SET_CURRENT_PROJECT_NEXT",
  SET_CURRENT_PROJECT_PREV: "SET_CURRENT_PROJECT_PREV"
};

export default projectsTypes;
