const projectsTypes = {
  SET_CURRENT_PROJECT_FIRST: "SET_CURRENT_PROJECT_FIRST",
  SET_CURRENT_PROJECT_SECOND: "SET_CURRENT_PROJECT_SECOND",
  SET_CURRENT_PROJECT_THIRD: "SET_CURRENT_PROJECT_THIRD",
  SET_CURRENT_PROJECT_FOURTH: "SET_CURRENT_PROJECT_FOURTH",
  SET_CURRENT_PROJECT_NEXT: "SET_CURRENT_PROJECT_NEXT",
  SET_CURRENT_PROJECT_PREV: "SET_CURRENT_PROJECT_PREV",
  GET_CURRENT_PROJECT: "GET_CURRENT_PROJECT",
  SET_CURRENT_IMAGE_NEXT: "SET_CURRENT_IMAGE_NEXT",
  SET_CURRENT_IMAGE_PREV: "SET_CURRENT_IMAGE_PREV"
};

export default projectsTypes;
