const blogsTypes = {
  SET_CURRENT_SET_NEXT: "SET_CURRENT_SET_NEXT",
  SET_CURRENT_SET_PREV: "SET_CURRENT_SET_PREV",
  SET_CURRENT_SET_BY_SLOT: "SET_CURRENT_SET_BY_SLOT",

  LOAD_ALL_BLOGPOSTS_START: "LOAD_ALL_BLOGPOSTS_START",
  LOAD_ALL_BLOGPOSTS_SUCCESS: "LOAD_ALL_BLOGPOSTS_SUCCESS",
  LOAD_ALL_BLOGPOSTS_FAILURE: "LOAD_ALL_BLOGPOSTS_FAILURE",
  CREATE_ONE_BLOGPOST_START: "CREATE_ONE_BLOGPOST_START",
  CREATE_ONE_BLOGPOST_SUCCESS: "CREATE_ONE_BLOGPOST_SUCCESS",
  CREATE_ONE_BLOGPOST_FAILURE: "CREATE_ONE_BLOGPOST_FAILURE",
  UPDATE_ONE_BLOGPOST_START: "UPDATE_ONE_BLOGPOST_START",
  UPDATE_ONE_BLOGPOST_SUCCESS: "UPDATE_ONE_BLOGPOST_SUCCESS",
  UPDATE_ONE_BLOGPOST_FAILURE: "UPDATE_ONE_BLOGPOST_FAILURE",
  DELETE_ONE_BLOGPOST_START: "DELETE_ONE_BLOGPOST_START",
  DELETE_ONE_BLOGPOST_SUCCESS: "DELETE_ONE_BLOGPOST_SUCCESS",
  DELETE_ONE_BLOGPOST_FAILURE: "DELETE_ONE_BLOGPOST_FAILURE",
  LIKE_ONE_BLOGPOST_START: "LIKE_ONE_BLOGPOST_START",
  LIKE_ONE_BLOGPOST_SUCCESS: "LIKE_ONE_BLOGPOST_SUCCESS",
  LIKE_ONE_BLOGPOST_FAILURE: "LIKE_ONE_BLOGPOST_FAILURE",
  DISLIKE_ONE_BLOGPOST_START: "DISLIKE_ONE_BLOGPOST_START",
  DISLIKE_ONE_BLOGPOST_SUCCESS: "DISLIKE_ONE_BLOGPOST_SUCCESS",
  DISLIKE_ONE_BLOGPOST_FAILURE: "DISLIKE_ONE_BLOGPOST_FAILURE",
  LIKE_ONE_BLOGPOST_LOCALLY: "LIKE_ONE_BLOGPOST_LOCALLY",
  DISLIKE_ONE_BLOGPOST_LOCALLY: "DISLIKE_ONE_BLOGPOST_LOCALLY"
};

export default blogsTypes;
