const usersTypes = {
  LOAD_ALL_USERS_START: "LOAD_ALL_USERS_START",
  LOAD_ALL_USERS_SUCCESS: "LOAD_ALL_USERS_SUCCESS",
  LOAD_ALL_USERS_FAILURE: "LOAD_ALL_USERS_FAILURE",
  CREATE_ONE_USER_START: "CREATE_ONE_USER_START",
  CREATE_ONE_USER_SUCCESS: "CREATE_ONE_USER_SUCCESS",
  CREATE_ONE_USER_FAILURE: "CREATE_ONE_USER_FAILURE",
  UPDATE_ONE_USER_START: "UPDATE_ONE_USER_START",
  UPDATE_ONE_USER_SUCCESS: "UPDATE_ONE_USER_SUCCESS",
  UPDATE_ONE_USER_FAILURE: "UPDATE_ONE_USER_FAILURE",
  DELETE_ONE_USER_START: "DELETE_ONE_USER_START",
  DELETE_ONE_USER_SUCCESS: "DELETE_ONE_USER_SUCCESS",
  DELETE_ONE_USER_FAILURE: "DELETE_ONE_USER_FAILURE",
  CLEAN_UP_USERS_FROM_STATE: "CLEAN_UP_USERS_FROM_STATE"
};

export default usersTypes;
