export const squares = {
  light: [
    {
      id: 1,
      width: 10,
      height: 10,
      posX: 10,
      posY: 24,
      shadow: true,
      color: "#fe3f2d",
    },
    {
      id: 2,
      width: 10,
      height: 10,
      posX: 30,
      posY: 34,
      shadow: true,
      color: "#ffaa2d",
    },
    {
      id: 3,
      width: 10,
      height: 10,
      posX: 20,
      posY: 34,
      shadow: true,
      color: "#00a8a9",
    },
    {
      id: 4,
      width: 10,
      height: 10,
      posX: 30,
      posY: 14,
      shadow: true,
      color: "#fe3f2d",
    },
    {
      id: 5,
      width: 10,
      height: 10,
      posX: 40,
      posY: 34,
      shadow: true,
      color: "#fed595",
    },
    {
      id: 6,
      width: 5,
      height: 5,
      posX: 5,
      posY: 5,
      shadow: true,
      color: "#fe3f2d",
    },
    {
      id: 7,
      width: 10,
      height: 10,
      posX: 20,
      posY: 24,
      shadow: true,
      color: "#ffaa2d",
    },
    {
      id: 8,
      width: 5,
      height: 5,
      posX: 15,
      posY: 10,
      shadow: true,
      color: "#00a8a9",
    },
    {
      id: 9,
      width: 10,
      height: 10,
      posX: 50,
      posY: 4,
      shadow: true,
      color: "#002a38",
    },
    {
      id: 10,
      width: 10,
      height: 10,
      posX: 40,
      posY: 14,
      shadow: true,
      color: "#00a8a9",
    },
    {
      id: 11,
      width: 10,
      height: 10,
      posX: 10,
      posY: 54,
      shadow: true,
      color: "#fed595",
    },
    {
      id: 12,
      width: 10,
      height: 10,
      posX: 30,
      posY: 24,
      shadow: true,
      color: "#002a38",
    },
    {
      id: 13,
      width: 10,
      height: 10,
      posX: 20,
      posY: 44,
      shadow: true,
      color: "#fe3f2d",
    },
    {
      id: 14,
      width: 10,
      height: 10,
      posX: 10,
      posY: 44,
      shadow: true,
      color: "#ffaa2d",
    },
    {
      id: 15,
      width: 10,
      height: 10,
      posX: 40,
      posY: 4,
      shadow: true,
      color: "#fed595",
    },
    {
      id: 16,
      width: 5,
      height: 5,
      posX: 110,
      posY: 40,
      shadow: true,
      color: "#d6d7d9",
    },
    {
      id: 17,
      width: 5,
      height: 5,
      posX: 100,
      posY: 45,
      shadow: true,
      color: "#c0c1c3",
    },
    {
      id: 18,
      width: 5,
      height: 5,
      posX: 105,
      posY: 45,
      shadow: true,
      color: "#d6d7d9",
    },
    {
      id: 20,
      width: 5,
      height: 5,
      posX: 100,
      posY: 50,
      shadow: true,
      color: "#bfc0c2",
    },
    {
      id: 21,
      width: 5,
      height: 5,
      posX: 95,
      posY: 50,
      shadow: true,
      color: "#bfc0c2",
    },
    {
      id: 22,
      width: 5,
      height: 5,
      posX: 90,
      posY: 45,
      shadow: true,
      color: "#d6d7d9",
    },
    {
      id: 23,
      width: 5,
      height: 5,
      posX: 90,
      posY: 55,
      shadow: true,
      color: "#bfc0c2",
    },
    {
      id: 24,
      width: 5,
      height: 5,
      posX: 110,
      posY: 50,
      shadow: true,
      color: "#d6d7d9",
    },
    {
      id: 25,
      width: 4,
      height: 4,
      posX: 2,
      posY: 40,
      shadow: true,
      color: "#ffaa2d",
    },
    {
      id: 26,
      width: 4,
      height: 4,
      posX: 110,
      posY: 15,
      shadow: true,
      color: "#fed595",
    },
    {
      id: 27,
      width: 4,
      height: 4,
      posX: 0,
      posY: 54,
      shadow: true,
      color: "#fe3f2d",
    },
    {
      id: 28,
      width: 4,
      height: 4,
      posX: 90,
      posY: 5,
      shadow: true,
      color: "#00a8a9",
    },
  ],
  dark: [
    {
      id: 1,
      width: 10,
      height: 10,
      posX: 10,
      posY: 24,
      shadow: true,
      color: "#397e67",
    },
    {
      id: 2,
      width: 10,
      height: 10,
      posX: 30,
      posY: 34,
      shadow: true,
      color: "#225e4a",
    },
    {
      id: 3,
      width: 10,
      height: 10,
      posX: 20,
      posY: 34,
      shadow: true,
      color: "#1c6d52",
    },
    {
      id: 4,
      width: 10,
      height: 10,
      posX: 30,
      posY: 14,
      shadow: true,
      color: "#447766",
    },
    {
      id: 5,
      width: 10,
      height: 10,
      posX: 40,
      posY: 34,
      shadow: true,
      color: "#173f32",
    },
    {
      id: 6,
      width: 5,
      height: 5,
      posX: 5,
      posY: 5,
      shadow: true,
      color: "#397e67",
    },
    {
      id: 7,
      width: 10,
      height: 10,
      posX: 20,
      posY: 24,
      shadow: true,
      color: "#225e4a",
    },
    {
      id: 8,
      width: 5,
      height: 5,
      posX: 15,
      posY: 10,
      shadow: true,
      color: "#1c6d52",
    },
    {
      id: 9,
      width: 10,
      height: 10,
      posX: 50,
      posY: 4,
      shadow: true,
      color: "#447766",
    },
    {
      id: 10,
      width: 10,
      height: 10,
      posX: 40,
      posY: 14,
      shadow: true,
      color: "#173f32",
    },
    {
      id: 11,
      width: 10,
      height: 10,
      posX: 10,
      posY: 54,
      shadow: true,
      color: "#397e67",
    },
    {
      id: 12,
      width: 10,
      height: 10,
      posX: 30,
      posY: 24,
      shadow: true,
      color: "#225e4a",
    },
    {
      id: 13,
      width: 10,
      height: 10,
      posX: 20,
      posY: 44,
      shadow: true,
      color: "#1c6d52",
    },
    {
      id: 14,
      width: 10,
      height: 10,
      posX: 10,
      posY: 44,
      shadow: true,
      color: "#447766",
    },
    {
      id: 15,
      width: 10,
      height: 10,
      posX: 40,
      posY: 4,
      shadow: true,
      color: "#397e67",
    },
    {
      id: 16,
      width: 5,
      height: 5,
      posX: 110,
      posY: 40,
      shadow: true,
      color: "#173f32",
    },
    {
      id: 17,
      width: 5,
      height: 5,
      posX: 100,
      posY: 45,
      shadow: true,
      color: "#1c6d52",
    },
    {
      id: 18,
      width: 5,
      height: 5,
      posX: 105,
      posY: 45,
      shadow: true,
      color: "#447766",
    },
    {
      id: 20,
      width: 5,
      height: 5,
      posX: 100,
      posY: 50,
      shadow: true,
      color: "#173f32",
    },
    {
      id: 21,
      width: 5,
      height: 5,
      posX: 95,
      posY: 50,
      shadow: true,
      color: "#397e67",
    },
    {
      id: 22,
      width: 5,
      height: 5,
      posX: 90,
      posY: 45,
      shadow: true,
      color: "#225e4a",
    },
    {
      id: 23,
      width: 5,
      height: 5,
      posX: 90,
      posY: 55,
      shadow: true,
      color: "#1c6d52",
    },
    {
      id: 24,
      width: 5,
      height: 5,
      posX: 110,
      posY: 50,
      shadow: true,
      color: "#447766",
    },
    {
      id: 25,
      width: 4,
      height: 4,
      posX: 2,
      posY: 40,
      shadow: true,
      color: "#173f32",
    },
    {
      id: 26,
      width: 4,
      height: 4,
      posX: 110,
      posY: 15,
      shadow: true,
      color: "#397e67",
    },
    {
      id: 27,
      width: 4,
      height: 4,
      posX: 0,
      posY: 54,
      shadow: true,
      color: "#225e4a",
    },
    {
      id: 28,
      width: 4,
      height: 4,
      posX: 90,
      posY: 5,
      shadow: true,
      color: "#1c6d52",
    },
  ],
};

export const ctaOptions = {
  light: {
    id: 30,
    width: 30,
    height: 7,
    posX: 50,
    posY: 50,
    shadow: true,
    color: "#002a38",
  },
  dark: {
    id: 30,
    width: 30,
    height: 7,
    posX: 50,
    posY: 50,
    shadow: true,
    color: "#DBDBDB",
  },
};
